/**
 * Build _fonts.mjs — base64-embeds the brand woff2 files so the render scripts
 * have ZERO network dependency (the render env is offline; Google Fonts @import
 * hangs). Run once; re-run only if the font set changes.
 *
 *   node scripts/story-assets/_build-fonts.mjs
 *
 * Sources the woff2 from sibling repos' @fontsource installs.
 */
import { readFileSync, writeFileSync, existsSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join, resolve } from 'node:path'
import { homedir } from 'node:os'

const HERE = dirname(fileURLToPath(import.meta.url))
const HOME = homedir()
const BEBAS = join(HOME, 'Workspace/dev/apps/letspepper/node_modules/@fontsource/bebas-neue/files')
const INTER = join(HOME, 'Workspace/dev/apps/letspepper/node_modules/@fontsource/inter/files')
const JET = join(HOME, 'Workspace/dev/apps/rally-hq/node_modules/@fontsource/jetbrains-mono/files')

// [family, weight, file]
const FACES = [
  ['Bebas Neue', 400, join(BEBAS, 'bebas-neue-latin-400-normal.woff2')],
  ['Inter', 400, join(INTER, 'inter-latin-400-normal.woff2')],
  ['Inter', 500, join(INTER, 'inter-latin-500-normal.woff2')],
  ['Inter', 600, join(INTER, 'inter-latin-600-normal.woff2')],
  ['Inter', 700, join(INTER, 'inter-latin-700-normal.woff2')],
  ['Inter', 800, join(INTER, 'inter-latin-800-normal.woff2')],
  ['JetBrains Mono', 400, join(JET, 'jetbrains-mono-latin-400-normal.woff2')],
  ['JetBrains Mono', 500, join(JET, 'jetbrains-mono-latin-500-normal.woff2')],
  ['JetBrains Mono', 700, join(JET, 'jetbrains-mono-latin-700-normal.woff2')],
]

const faces = FACES.map(([family, weight, file]) => {
  if (!existsSync(file)) throw new Error(`Missing font file: ${file}`)
  const b64 = readFileSync(file).toString('base64')
  return `@font-face{font-family:'${family}';font-style:normal;font-weight:${weight};font-display:block;src:url(data:font/woff2;base64,${b64}) format('woff2')}`
}).join('\n')

const out = `/* AUTO-GENERATED by _build-fonts.mjs — base64 woff2, offline-safe. Do not edit. */
export const FONTS = \`${faces}\`
`
const target = resolve(HERE, '_fonts.mjs')
writeFileSync(target, out)
console.log('Wrote', target, `(${(out.length / 1024).toFixed(0)} KB, ${FACES.length} faces)`)
